server:
  port: 8762
spring:
  application:
    name: config-server-demo
  profiles:
    active: subversion #从svn上读取时必加
  cloud:
    config:
      server:
        svn:
          uri: svn://10.128.32.189/
          search-paths:  svndeconfig  #配置文件所在根目录
          default-label: trunk    #配置文件分支
          username: jack
          password: jack
nickName: config from  git nicknamefdsdfsdfs 